stages:
    - build
    - dropbox

build-apostila:
    script: "build-apostila.sh"
    stage: build
    artifacts:
        name: "Apostilas"
        paths:
            - apostilas/

upload-dropbox:
    script: "upload-dropbox.sh"
    stage: dropbox
    only:
        refs:
            - master
    dependencies:
        - build-apostila

